import { useState } from "react";
import { useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";
import { ArrowLeft, Edit2, Save, Send, Sparkles } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Streamdown } from "streamdown";

export default function ReviewDraftPreview() {
  const [, params] = useRoute("/reviews/draft/:personId");
  const personId = params?.personId ? parseInt(params.personId) : 0;
  const { user } = useAuth();
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState<Record<string, string>>({});

  const { data: person } = trpc.person.getById.useQuery({ personId });
  const { data: reviewData, isLoading } = trpc.review.getDraftByPerson.useQuery({
    personId,
    tenantId: user?.id || 0,
  });

  // Parse review content from JSON
  const review = reviewData ? {
    ...reviewData,
    valuesAlignment: reviewData.aiGeneratedDraft ? JSON.parse(reviewData.aiGeneratedDraft).values : null,
    performanceDimensions: reviewData.aiGeneratedDraft ? JSON.parse(reviewData.aiGeneratedDraft).performance : null,
    fitDetermination: reviewData.aiGeneratedDraft ? JSON.parse(reviewData.aiGeneratedDraft).fit : null,
    developmentRecommendations: reviewData.aiGeneratedDraft ? JSON.parse(reviewData.aiGeneratedDraft).development : null,
  } : null;

  const saveDraft = trpc.review.saveDraft.useMutation({
    onSuccess: () => {
      toast.success("Review draft saved");
      setIsEditing(false);
    },
    onError: () => {
      toast.error("Failed to save draft");
    },
  });

  const finalizeReview = trpc.review.finalize.useMutation({
    onSuccess: () => {
      toast.success("Review finalized and sent to employee");
      window.history.back();
    },
    onError: () => {
      toast.error("Failed to finalize review");
    },
  });

  const handleSave = () => {
    if (!review) return;
    
    saveDraft.mutate({
      reviewId: review.id,
      content: editedContent,
    });
  };

  const handleFinalize = () => {
    if (!review) return;

    if (confirm("Are you sure you want to finalize and send this review to the employee? This action cannot be undone.")) {
      finalizeReview.mutate({
        reviewId: review.id,
        content: editedContent,
      });
    }
  };

  if (isLoading) {
    return (
      <div className="container py-8">
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      </div>
    );
  }

  if (!review) {
    return (
      <div className="container py-8">
        <Card className="p-12 text-center">
          <Sparkles className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
          <h2 className="text-xl font-semibold mb-2">No Review Draft Available</h2>
          <p className="text-muted-foreground mb-6">
            The Living Review Draft will be auto-generated after collecting 5 observations.
          </p>
          <Button onClick={() => window.history.back()}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Go Back
          </Button>
        </Card>
      </div>
    );
  }

  const sections = [
    {
      title: "Values Alignment",
      key: "values",
      content: review.valuesAlignment || "No data available yet.",
    },
    {
      title: "Performance Dimensions",
      key: "performance",
      content: review.performanceDimensions || "No data available yet.",
    },
    {
      title: "Fit Determination",
      key: "fit",
      content: review.fitDetermination || "No data available yet.",
    },
    {
      title: "Development Recommendations",
      key: "development",
      content: review.developmentRecommendations || "No data available yet.",
    },
  ];

  return (
    <div className="container py-8 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => window.history.back()}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold">Performance Review Draft</h1>
            <p className="text-muted-foreground">
              {person?.name} • Auto-generated by AI
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {review.status === "DRAFT" && (
            <Badge variant="outline" className="bg-amber-50 text-amber-700 border-amber-200">
              Draft
            </Badge>
          )}
          {review.status === "FINAL" && (
            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
              Finalized
            </Badge>
          )}
        </div>
      </div>

      {/* AI Generation Info */}
      <Card className="p-4 mb-6 bg-blue-50 border-blue-200">
        <div className="flex items-start gap-3">
          <Sparkles className="h-5 w-5 text-blue-600 mt-0.5" />
          <div className="flex-1">
            <p className="text-sm font-medium text-blue-900">
              AI-Generated Living Review
            </p>
            <p className="text-sm text-blue-700 mt-1">
              This review was automatically generated based on observations, evidence, and performance data. 
              You can edit any section before finalizing.
            </p>
          </div>
        </div>
      </Card>

      {/* Review Sections */}
      <div className="space-y-6">
        {sections.map((section) => (
          <Card key={section.key} className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">{section.title}</h2>
              {!isEditing && review.status === "DRAFT" && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setIsEditing(true);
                    setEditedContent({
                      ...editedContent,
                      [section.key]: section.content,
                    });
                  }}
                >
                  <Edit2 className="h-4 w-4 mr-2" />
                  Edit
                </Button>
              )}
            </div>
            <Separator className="mb-4" />
            {isEditing ? (
              <Textarea
                value={editedContent[section.key] || section.content}
                onChange={(e) =>
                  setEditedContent({
                    ...editedContent,
                    [section.key]: e.target.value,
                  })
                }
                className="min-h-[200px] font-sans"
                placeholder={`Edit ${section.title.toLowerCase()}...`}
              />
            ) : (
              <div className="prose prose-sm max-w-none">
                <Streamdown>{section.content}</Streamdown>
              </div>
            )}
          </Card>
        ))}
      </div>

      {/* Actions */}
      {review.status === "DRAFT" && (
        <div className="flex items-center justify-end gap-3 mt-8">
          {isEditing && (
            <>
              <Button
                variant="outline"
                onClick={() => {
                  setIsEditing(false);
                  setEditedContent({});
                }}
              >
                Cancel
              </Button>
              <Button onClick={handleSave} disabled={saveDraft.isPending}>
                <Save className="h-4 w-4 mr-2" />
                Save Draft
              </Button>
            </>
          )}
          {!isEditing && (
            <Button onClick={handleFinalize} disabled={finalizeReview.isPending}>
              <Send className="h-4 w-4 mr-2" />
              Finalize & Send to Employee
            </Button>
          )}
        </div>
      )}
    </div>
  );
}
